# Generated by Django 5.0.9 on 2024-10-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="test",
            new_name="text",
        ),
    ]
